var smdConfig = {
	"desktop":{
		'content-head':{
			"smd1":{
				"triggerDom":".content-head .text-box .head-text .right-box",
				'triggerPlay':0.9,
				'triggerReset':0.99,
				'triggerOffset':0,
				'ani_type':'base',
				'ani_align':'start',
				'ani_stagger_t':0.1,
				'ani':[{
					'change':[{
						'proper':'opacity',
						'from':0,
						'to':1
					},{
						'proper':'scale',
						'from':0.85,
						'to':1
					}],
					'duration':0.5,
					'dom':'.content-head .text-box .head-text .right-box'
				}],
				'needbroadcast':false,
				'inited':false,
				'debug':false,
				'enable':true,
				'reset':true,
				'widthScope':[1,1000000]
			},
			"smd2":{
				"triggerDom":".content-head .quiz-box",
				'triggerPlay':0.9,
				'triggerReset':0.99,
				'triggerOffset':0,
				'ani_type':'base',
				'ani_align':'start',
				'ani_stagger_t':0.1,
				'ani':[{
					'change':[{
						'proper':'opacity',
						'from':0,
						'to':1
					},{
						'proper':'scale',
						'from':0.9,
						'to':1
					}],
					'duration':0.5,
					'dom':'.content-head .quiz-box .anim-box'
				}],
				'needbroadcast':false,
				'inited':false,
				'debug':false,
				'enable':true,
				'reset':true,
				'widthScope':[1,1000000]
			}
		},
		'content-driving':{
			"smd1":{
				"triggerDom":".content-driving .quiz-box",
				'triggerPlay':0.9,
				'triggerReset':0.99,
				'triggerOffset':0,
				'ani_type':'base',
				'ani_align':'start',
				'ani_stagger_t':0.1,
				'ani':[{
					'change':[{
						'proper':'opacity',
						'from':0,
						'to':1
					},{
						'proper':'scale',
						'from':0.9,
						'to':1
					}],
					'duration':0.5,
					'dom':'.content-driving .quiz-box .anim-box'
				}],
				'needbroadcast':false,
				'inited':false,
				'debug':false,
				'enable':true,
				'reset':true,
				'widthScope':[1,1000000]
			}
		},
		'content-carousel':{
			"smd1":{
				"triggerDom":".content-carousel",
				'triggerPlay':0.9,
				'triggerReset':0.99,
				'triggerOffset':0,
				'ani_type':'base',
				'ani_align':'start',
				'ani_stagger_t':0.1,
				'ani':[{
					'change':[{
						'proper':'opacity',
						'from':0,
						'to':1
					},{
						'proper':'scale',
						'from':0.9,
						'to':1
					}],
					'duration':0.5,
					'dom':'.content-carousel .anim-box'
				}],
				'needbroadcast':false,
				'inited':false,
				'debug':false,
				'enable':true,
				'reset':true,
				'widthScope':[1,1000000]
			}
		},
		'content-power':{
			"smd1":{
				"triggerDom":".content-power .quiz-box",
				'triggerPlay':0.9,
				'triggerReset':0.99,
				'triggerOffset':0,
				'ani_type':'base',
				'ani_align':'start',
				'ani_stagger_t':0.1,
				'ani':[{
					'change':[{
						'proper':'opacity',
						'from':0,
						'to':1
					},{
						'proper':'scale',
						'from':0.9,
						'to':1
					}],
					'duration':0.5,
					'dom':'.content-power .quiz-box .anim-box'
				}],
				'needbroadcast':false,
				'inited':false,
				'debug':false,
				'enable':true,
				'reset':true,
				'widthScope':[1,1000000]
			}
		},
		'content-night':{
			"smd1":{
				"triggerDom":".content-night .quiz-box",
				'triggerPlay':0.9,
				'triggerReset':0.99,
				'triggerOffset':0,
				'ani_type':'base',
				'ani_align':'start',
				'ani_stagger_t':0.1,
				'ani':[{
					'change':[{
						'proper':'opacity',
						'from':0,
						'to':1
					},{
						'proper':'scale',
						'from':0.9,
						'to':1
					}],
					'duration':0.5,
					'dom':'.content-night .quiz-box .anim-box'
				}],
				'needbroadcast':false,
				'inited':false,
				'debug':false,
				'enable':true,
				'reset':true,
				'widthScope':[1,1000000]
			}
		},
		'content-how':{
			"smd1":{
				"triggerDom":".content-how .quiz-box",
				'triggerPlay':0.9,
				'triggerReset':0.99,
				'triggerOffset':0,
				'ani_type':'base',
				'ani_align':'start',
				'ani_stagger_t':0.1,
				'ani':[{
					'change':[{
						'proper':'opacity',
						'from':0,
						'to':1
					},{
						'proper':'scale',
						'from':0.9,
						'to':1
					}],
					'duration':0.5,
					'dom':'.content-how .quiz-box .anim-box'
				}],
				'needbroadcast':false,
				'inited':false,
				'debug':false,
				'enable':true,
				'reset':true,
				'widthScope':[1,1000000]
			}
		},
		'content-footer':{
			"smd1":{
				"triggerDom":".content-footer",
				'triggerPlay':0.9,
				'triggerReset':0.99,
				'triggerOffset':0,
				'ani_type':'base',
				'ani_align':'start',
				'ani_stagger_t':0.1,
				'ani':[{
					'change':[{
						'proper':'opacity',
						'from':0,
						'to':1
					},{
						'proper':'scale',
						'from':0.9,
						'to':1
					}],
					'duration':0.5,
					'dom':'.content-footer .content-box .copy .title'
				}],
				'needbroadcast':false,
				'inited':false,
				'debug':false,
				'enable':true,
				'reset':true,
				'widthScope':[1,1000000]
			},
			"smd2":{
				"triggerDom":".content-footer",
				'triggerPlay':0.9,
				'triggerReset':0.99,
				'triggerOffset':0,
				'ani_type':'base',
				'ani_align':'start',
				'ani_stagger_t':0.1,
				'ani':[{
					'change':[{
						'proper':'opacity',
						'from':0,
						'to':1
					},{
						'proper':'scale',
						'from':0.9,
						'to':1
					}],
					'duration':0.5,
					'dom':'.content-footer .content-box .copy .cta'
				}],
				'needbroadcast':false,
				'inited':false,
				'debug':false,
				'enable':true,
				'reset':true,
				'widthScope':[1,1000000]
			},
			"smd3":{
				"triggerDom":".content-footer",
				'triggerPlay':0.9,
				'triggerReset':0.99,
				'triggerOffset':0,
				'ani_type':'base',
				'ani_align':'start',
				'ani_stagger_t':0.1,
				'ani':[{
					'change':[{
						'proper':'opacity',
						'from':0,
						'to':1
					},{
						'proper':'scale',
						'from':0.9,
						'to':1
					}],
					'duration':0.5,
					'dom':'.content-footer .content-box .logo'
				}],
				'needbroadcast':false,
				'inited':false,
				'debug':false,
				'enable':true,
				'reset':true,
				'widthScope':[1,1000000]
			}
		}
	},
	"mobile":{
		'content-head':{
			"smd1":{
				"triggerDom":".content-head .text-box .head-text .right-box",
				'triggerPlay':0.9,
				'triggerReset':0.99,
				'triggerOffset':0,
				'ani_type':'base',
				'ani_align':'start',
				'ani_stagger_t':0.1,
				'ani':[{
					'change':[{
						'proper':'opacity',
						'from':0,
						'to':1
					},{
						'proper':'scale',
						'from':0.85,
						'to':1
					}],
					'duration':0.5,
					'dom':'.content-head .text-box .head-text .right-box'
				}],
				'needbroadcast':false,
				'inited':false,
				'debug':false,
				'enable':true,
				'reset':true,
				'widthScope':[1,1000000]
			},
			"smd2":{
				"triggerDom":".content-head .quiz-box",
				'triggerPlay':0.9,
				'triggerReset':0.99,
				'triggerOffset':0,
				'ani_type':'base',
				'ani_align':'start',
				'ani_stagger_t':0.1,
				'ani':[{
					'change':[{
						'proper':'opacity',
						'from':0,
						'to':1
					},{
						'proper':'scale',
						'from':0.9,
						'to':1
					}],
					'duration':0.5,
					'dom':'.content-head .quiz-box .anim-box'
				}],
				'needbroadcast':false,
				'inited':false,
				'debug':false,
				'enable':true,
				'reset':true,
				'widthScope':[1,1000000]
			}
		},
		'content-driving':{
			"smd1":{
				"triggerDom":".content-driving .quiz-box",
				'triggerPlay':0.9,
				'triggerReset':0.99,
				'triggerOffset':0,
				'ani_type':'base',
				'ani_align':'start',
				'ani_stagger_t':0.1,
				'ani':[{
					'change':[{
						'proper':'opacity',
						'from':0,
						'to':1
					},{
						'proper':'scale',
						'from':0.9,
						'to':1
					}],
					'duration':0.5,
					'dom':'.content-driving .quiz-box .anim-box'
				}],
				'needbroadcast':false,
				'inited':false,
				'debug':false,
				'enable':true,
				'reset':true,
				'widthScope':[1,1000000]
			}
		},
		'content-carousel':{
			"smd1":{
				"triggerDom":".content-carousel",
				'triggerPlay':0.9,
				'triggerReset':0.99,
				'triggerOffset':0,
				'ani_type':'base',
				'ani_align':'start',
				'ani_stagger_t':0.1,
				'ani':[{
					'change':[{
						'proper':'opacity',
						'from':0,
						'to':1
					},{
						'proper':'scale',
						'from':0.9,
						'to':1
					}],
					'duration':0.5,
					'dom':'.content-carousel .anim-box'
				}],
				'needbroadcast':false,
				'inited':false,
				'debug':false,
				'enable':true,
				'reset':true,
				'widthScope':[1,1000000]
			}
		},
		'content-power':{
			"smd1":{
				"triggerDom":".content-power .quiz-box",
				'triggerPlay':0.9,
				'triggerReset':0.99,
				'triggerOffset':0,
				'ani_type':'base',
				'ani_align':'start',
				'ani_stagger_t':0.1,
				'ani':[{
					'change':[{
						'proper':'opacity',
						'from':0,
						'to':1
					},{
						'proper':'scale',
						'from':0.9,
						'to':1
					}],
					'duration':0.5,
					'dom':'.content-power .quiz-box .anim-box'
				}],
				'needbroadcast':false,
				'inited':false,
				'debug':false,
				'enable':true,
				'reset':true,
				'widthScope':[1,1000000]
			}
		},
		'content-night':{
			"smd1":{
				"triggerDom":".content-night .quiz-box",
				'triggerPlay':0.9,
				'triggerReset':0.99,
				'triggerOffset':0,
				'ani_type':'base',
				'ani_align':'start',
				'ani_stagger_t':0.1,
				'ani':[{
					'change':[{
						'proper':'opacity',
						'from':0,
						'to':1
					},{
						'proper':'scale',
						'from':0.9,
						'to':1
					}],
					'duration':0.5,
					'dom':'.content-night .quiz-box .anim-box'
				}],
				'needbroadcast':false,
				'inited':false,
				'debug':false,
				'enable':true,
				'reset':true,
				'widthScope':[1,1000000]
			}
		},
		'content-how':{
			"smd1":{
				"triggerDom":".content-how .quiz-box",
				'triggerPlay':0.9,
				'triggerReset':0.99,
				'triggerOffset':0,
				'ani_type':'base',
				'ani_align':'start',
				'ani_stagger_t':0.1,
				'ani':[{
					'change':[{
						'proper':'opacity',
						'from':0,
						'to':1
					},{
						'proper':'scale',
						'from':0.9,
						'to':1
					}],
					'duration':0.5,
					'dom':'.content-how .quiz-box .anim-box'
				}],
				'needbroadcast':false,
				'inited':false,
				'debug':false,
				'enable':true,
				'reset':true,
				'widthScope':[1,1000000]
			}
		}
		/*'content-footer':{
			"smd1":{
				"triggerDom":".content-footer",
				'triggerPlay':0.9,
				'triggerReset':0.99,
				'triggerOffset':0,
				'ani_type':'base',
				'ani_align':'start',
				'ani_stagger_t':0.1,
				'ani':[{
					'change':[{
						'proper':'opacity',
						'from':0,
						'to':1
					},{
						'proper':'scale',
						'from':0.9,
						'to':1
					}],
					'duration':0.5,
					'dom':'.content-footer .content-box'
				}],
				'needbroadcast':false,
				'inited':false,
				'debug':false,
				'enable':true,
				'reset':true,
				'widthScope':[1,640]
			}
		}*/
	}
};
